/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yuan Dimianta
 */
public class ChangePin extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public ChangePin() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        changeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        confirmPinField = new javax.swing.JTextField();
        pinField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SILAHKAN MASUKKAN PIN BARU ANDA ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        changeBtn.setText("GANTI PIN");
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(changeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 140, 30));

        backBtn.setText("KEMBALI");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 140, 30));

        confirmPinField.setBackground(new java.awt.Color(255, 255, 255));
        confirmPinField.setForeground(new java.awt.Color(0, 0, 0));
        confirmPinField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmPinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                confirmPinFieldKeyTyped(evt);
            }
        });
        getContentPane().add(confirmPinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 330, 40));

        pinField.setBackground(new java.awt.Color(255, 255, 255));
        pinField.setForeground(new java.awt.Color(0, 0, 0));
        pinField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinFieldKeyTyped(evt);
            }
        });
        getContentPane().add(pinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 330, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KONFIRMASI PIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PIN BARU");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        ImageIcon image = new ImageIcon("D:\\Yuan Dimianta\\Kuliah\\Semester 5\\PBO\\Praktikum\\projectPBO\\BankManagementSystem\\src\\Assets\\atm.jpg");
        background.setIcon(image); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 960, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinFieldKeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if ((!Character.isDigit(input)) || (pinField.getText().length() > 5)) {
            evt.consume();
        }
    }//GEN-LAST:event_pinFieldKeyTyped

    private void confirmPinFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPinFieldKeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if ((!Character.isDigit(input)) || (confirmPinField.getText().length() > 5)) {
            evt.consume();
        }
    }//GEN-LAST:event_confirmPinFieldKeyTyped

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }// GEN-LAST:event_backBtnActionPerformed

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_changeBtnActionPerformed
        // TODO add your handling code here:
        String pin = pinField.getText();
        String confirmPin = confirmPinField.getText();
        if (pin.equals(confirmPin)) {
            int fixedPin = Integer.parseInt(pin);
            Conn.changePin(fixedPin);
        } else {
            JOptionPane.showMessageDialog(null, "PIN tidak sesuai");
        }
    }// GEN-LAST:event_changeBtnActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel background;
    private javax.swing.JButton changeBtn;
    private javax.swing.JTextField confirmPinField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pinField;
    // End of variables declaration//GEN-END:variables
}
