/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;

import javax.swing.ImageIcon;

/**
 *
 * @author Yuan Dimianta
 */
public class Menu extends javax.swing.JFrame implements MouseMotionListener{

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(this);
        addMouseMotionListener(this);
        Session.setFrame(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        setorBtn = new javax.swing.JButton();
        pinChangeBtn = new javax.swing.JButton();
        transferBtn = new javax.swing.JButton();
        withdrawBtn = new javax.swing.JButton();
        balanceBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Select Your Transaction");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        setorBtn.setText("SETOR TUNAI");
        setorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorBtnActionPerformed(evt);
            }
        });
        getContentPane().add(setorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 140, 30));

        pinChangeBtn.setText("GANTI PIN");
        pinChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinChangeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(pinChangeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 140, 30));

        transferBtn.setText("TRANSFER");
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });
        getContentPane().add(transferBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 140, 30));

        withdrawBtn.setText("PENARIKAN TUNAI");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 140, 30));

        balanceBtn.setText("INFORMASI SALDO");
        balanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(balanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 140, 30));

        cancelBtn.setText("BATAL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 140, 30));

        ImageIcon image = new ImageIcon("D:\\Yuan Dimianta\\Kuliah\\Semester 5\\PBO\\Praktikum\\projectPBO\\BankManagementSystem\\src\\Assets\\atm.jpg");
        background.setIcon(image); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 960, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinChangeBtnActionPerformed
        // TODO add your handling code here:
        new ChangePin().setVisible(true);
        dispose();
    }//GEN-LAST:event_pinChangeBtnActionPerformed

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        // TODO add your handling code here:
        new Transfer().setVisible(true);
        dispose();
    }//GEN-LAST:event_transferBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void setorBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_setorBtnActionPerformed
        // TODO add your handling code here:
        new Deposit().setVisible(true);
        dispose();
    }// GEN-LAST:event_setorBtnActionPerformed

    private void balanceBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_balanceBtnActionPerformed
        // TODO add your handling code here:
        new Balance().setVisible(true);
        dispose();
    }// GEN-LAST:event_balanceBtnActionPerformed

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_withdrawBtnActionPerformed
        // TODO add your handling code here:
        new Withdraw().setVisible(true);
        dispose();
    }// GEN-LAST:event_withdrawBtnActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton balanceBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pinChangeBtn;
    private javax.swing.JButton setorBtn;
    private javax.swing.JButton transferBtn;
    private javax.swing.JButton withdrawBtn;
    // End of variables declaration//GEN-END:variables
    @Override
    public void mouseDragged(MouseEvent e) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'mouseDragged'");
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        // TODO Auto-generated method stub
        AFKChecker.resetTimer();
    }
}
